### ISSUE TITLE
Classifying differential oscillation

### ISSUE THREAD

**Issue by ATpoint** [hugheylab/limorhyde#8]
Hello,

first of all thank you for developing and maintaining this package. It runs smoothly and documentation is clear. 

I have a question towards further classifying the results from a differential rhythmicity analysis. Say one followed the vignette and then obtained differentially rhythmic genes under a given FDR. What I would like to get is a classification basically as in the attached image from the [compareRhythms](https://febs.onlinelibrary.wiley.com/doi/10.1111/febs.16095) paper. Is there any strategy you could think of downsteam of limorhyde that applies here? 

Edit: A second question. I went through the ZeitZeiger code and paper and saw that the functions to calculate the rhythmic properties for each feature (amplitude etc) was deprecated from it with the recommendation to now use limorhyde. Still, I see no part in the limorhyde vignette on how to calculate these features. Could you comment on that?

Thank you!

![diffr](https://user-images.githubusercontent.com/21218078/175962154-dcebba6d-5f8f-4fd0-a6c6-0b0f9f3b4ea1.png)

**Comment by ATpoint** [comment]
¯\_(ツ)_/¯

**Comment by JSchoenbachler** [comment]
Hey @ATpoint , did you close this due to no response?

If so, you might want to re-open and let me know. Apologies for no response, but our lab PI (who originally wrote the package, and is maintainer) was out of office last week, but just returned today.

**Comment by michael-mazzucco** [comment]
I was also hoping for a reply on this, should I open it up as a separate issue?

**Comment by jakejh** [comment]
Hi @mickmars51 . limorhyde itself does not calculate any rhythmic properties or try to classify genes into those categories mentioned above. Instead, you can use it to get adjusted p-values of rhythmicity in one condition and differential rhythmicity between conditions. To calculate other rhythm-related properties, you could try [circacompare](https://cran.r-project.org/package=circacompare) or a new method we're working on called [limorhyde2](https://limorhyde2.hugheylab.org/).
